name: Publish to RubyGems

on:
  release:
    types: [published]

jobs:
  publish:
    name: Build & Push Gem
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"

      - name: Build gem
        run: gem build zerodrop.gemspec

      - name: Push to RubyGems
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: gem push zerodrop-*.gem
